doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Framework:
                type: annotation
                dir: '%kernel.project_dir%/src/Framework'
                prefix: 'App\Framework'

            TimeTracking:
                type: annotation
                dir: '%kernel.project_dir%/src/TimeTracking'
                prefix: 'App\TimeTracking'

