version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./docker/ssl:/etc/ssl"
      - "./public:/var/www/html/public"
    ports:
      - "8000:80"
#      - "3000:443"
    environment:
      - NGINX_HOST=locahost
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - mysql
      - redis

  php:
    build:
      dockerfile: "./docker/php/Dockerfile"
      context: .
    restart: always
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes